permalink: /:title 

pygments: true

title : Three Sisters
tagline: We only grow and thrive together.
author : 
  name : Nicholas Gunner
  email : gunnernr@gmail.com
  github : ngunner
  twitter : nicholas_gunner
  web : http://www.nicholasgunner.com

production_url : http://threesisters.us

baseurl : http://threesisters.us
   
        
analytics :
  google : 
    tracking_id : ''


authors:
  ngunner:
    name: Nicholas Gunner
    display_name: Nicholas Gunner
    bio: New Media Manager at SUNY Fredonia. Multimedia Storyteller.
    gravatar: http://www.gravatar.com/avatar/a85d870dce3cc177b6b0016a1ef4c200.png
    email: gunnernr@gmail.com
    web: http://www.nicholasgunner.com
    twitter: nicholas_gunner
    github: ngunner
   
  
timezone : America/New_York

prose:
  rooturl: '_posts'
  siteurl: 'http://www.threesisters.us'
  metadata:
    _posts/farms:
      - name: "layout"
        field:
          element: "hidden"
          value: "page"
      - name: "type"
        field:
          element: "hidden"
          value: "farm"
      - name: "published"
        field:
          element: "checkbox"
          label: "Published?"
          value: "true"
      - name: "title"
        field:
          element: "text"
          label: "Farm name"
      - name: "latitude"
        field:
          element: "text"
          label: "Latitude"
      - name: "longitude"
        field:
          element: "text"
          label: "Longitude"
      - name: "produce"
        field:
          element: "multiselect"
          label: "Produce offered"
          placeholder: "Choose produce"
          options:
            - name: "Apples"
              value: "Apples" 
            - name: "Asparagus"
              value: "Asparagus"
            - name: "Basil"
              value: "Basil"
            - name: "Beans (Green / Provider)"
              value: "Beans (Green / Provider)"
            - name: "Beans (Italian)"
              value: "Beans (Italian)"
            - name: "Beans (Yellow / Wax)"
              value: "Beans (Yellow / Wax)"
            - name: "Beans (Pole)"
              value: "Beans (Pole)"
            - name: "Beets"
              value: "Beets"
            - name: "Blue Berries"
              value: "Blue Berries"
            - name: "Broccoli"
              value: "Broccoli"
            - name: "Cabbage"
              value: "Cabbage"
            - name: "Cantaloupe"
              value: "Cantaloupe"
            - name: "Carrots"
              value: "Carrots"
            - name: "Chard"
              value: "Chard"
            - name: "Cilantro"
              value: "Cilantro"
            - name: "Corn"
              value: "Corn"
            - name: "Cress"
              value: "Cress"
            - name: "Cucumbers (Pickling)"
              value: "Cucumbers (Pickling)"
            - name: "Cucumbers (slicing)"
              value: "Cucumbers (slicing)"
            - name: "Dill"
              value: "Dill"
            - name: "Eggplant"
              value: "Eggplant"
            - name: "Garlic Scapes"
              value: "Garlic Scapes"
            - name: "Gourd (small fruited)"
              value: "Gourd (small fruited)"
            - name: "Grapes"
              value: "Grapes"
            - name: "Kale"
              value: "Kale"
            - name: "Leeks"
              value: "Leeks"
            - name: "Lettuce Heads"
              value: "Lettuce Heads"
            - name: "Lettuce Mix"
              value: "Lettuce Mix"
            - name: "Mushrooms"
              value: "mushrooms"
            - name: "Nasturtium"
              value: "Nasturtium"
            - name: "Onions"
              value: "Onions"
            - name: "Parsley"
              value: "Parsley"
            - name: "Pears"
              value: "Pears"
            - name: "Peas (Shell)"
              value: "Peas (Shell)"
            - name: "Peas (Snow)"
              value: "Peas (Snow)"
            - name: "Peas (Sugar Snap)"
              value: "Peas (Sugar Snap)"
            - name: "Peppers (sweet)"
              value: "Peppers (sweet)"
            - name: "Peppers (hot)"
              value: "Peppers (hot)"
            - name: "Peppers (Lunchbox)"
              value: "Peppers (Lunchbox)"
            - name: "Potatoes (Fingerlings)"
              value: "Potatoes (Fingerlings)"
            - name: "Potatoes (Regular)"
              value: "Potatoes (Regular)"
            - name: "Pumpkins (Miniature)"
              value: "Pumpkins (Miniature)"
            - name: "Pumpkins (Regular)"
              value: "Pumpkins (Regular)"
            - name: "Radish"
              value: "Radish"
            - name: "Radish (Daikon)"
              value: "Radish (Daikon)"
            - name: "Squash (winter)"
              value: "Squash (winter)"
            - name: "Squash (summer)"
              value: "Squash (summer)"
            - name: "Strawberries"
              value: "strawberries"
            - name: "Tomatoes (Cherry)"
              value: "Tomatoes (Cherry)"
            - name: "Tomatoes (Heirloom)"
              value: "Tomatoes (Heirloom)"
            - name: "Tomatoes (Regular)"
              value: "Tomatoes (Regular)"
            - name: "Turnips"
              value: "Turnips"
            - name: "Watermelon"
              value: "Watermelon"              
      - name: "eggs"
        field:
          element: "multiselect"
          label: "Eggs offered"
          placeholder: "Choose eggs"
          options:
            - name: "Eggs (Chicken)"
              value: "Eggs (Chicken)"
            - name: "Eggs (Duck)"
              value: "Eggs (Duck)"
            - name: "Eggs (Turkey)"
              value: "Eggs (Turkey)"
      - name: "meats"
        field:
          element: "multiselect"
          label: "Meats offered"
          placeholder: "Choose meats"
          options:
            - name: "Beef"
              value: "Beef"
            - name: "Chicken"
              value: "Chicken"
            - name: "Goat"
            - value: "Goat"
            - name: "Lamb"
              value: "Lamb"
            - name: "Mutton"
              value: "Mutton"
            - name: "Pork"
              value: "Pork"
            - name: "Rabbit"
              value: "Rabbit"
            - name: "Turkey"
              value: "Turkey"
      - name: "dairy"
        field:
          element: "multiselect"
          label: "Dairy offered"
          placeholder: "Choose dairy"
          options:
            - name: "Milk (Cow, Pasteurized)"
              value: "Milk (Cow, Pasteurized)"
            - name: "Milk (Cow, Raw)"
              value: "Milk (Cow, Raw)"
            - name: "Milk (Goat, Pasteurized)"
              value: "Milk (Goat, Pasteurized)"
            - name: "Cheese (Cow)"
              value: "Cheese (Cow)"
            - name: "Cheese (Goat)"
              value: "Cheese (Goat)"
            - name: "Yogurt"
              value: "Yogurt"
      - name: "valueAddedProducts"
        field:
          element: "multiselect"
          label: "Value added products offered"
          placeholder: "Choose Value added products"
          options:
            - name: "Apple Cider"
              value: "Apple Cider"
            - name: "Bread"
              value: "Bread"
            - name: "Jams"
              value: "Jams"
            - name: "Jellies"
              value: "Jellies"
            - name: "Maple Cream"
              value: "Maple Cream"
            - name: "Maple Syrup"
              value: "Maple Syrup"
            - name: "Maple Vinegar"
              value: "Maple Vinegar"
            - name: "Oat Meal"
              value: "Oat Meal"